name: Build
on:
  push:
    branches:
      - development
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deployheroku:
    name: deployHeroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_DEV}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          NODE_ENV: production
  laraveldeploy:
    name: laraveldeploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1 # This is the action
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "dist"
          dist_target_dir: "public_html"
          delete: "true"
          exclude: "'^logs/' '^README.md'"